# Test against this version of Node.js
environment:
  matrix:
  - nodejs_version: 6

# Install scripts, run after repo cloning
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

# Post install test scripts
test_script:
  # Useful info for debugging
  - node --version
  - npm --version
  # run tests
  - npm test

# Don't build
build: off
